const menu1 = document.querySelector('#menu1')
const about_us = document.querySelector('#about_us')
const rules = document.querySelector('#rules')
const contact = document.querySelector('#contact')
const etc = document.querySelector('#etc')

const menuDisplay = document.querySelector('.main_display')
const about_usDisplay = document.querySelector('.about_us_display')
const rulesDisplay = document.querySelector('.rules_display')
const contactDisplay = document.querySelector('.contact_display')
const etcDisplay = document.querySelector('.etc_display')
